#!/bin/sh

. /lib/partman/lib/base.sh
. /lib/partman/lib/recipes.sh
. /lib/partman/lib/auto-shared.sh

dev=$1
cd $dev

[ -f size ] || exit 1
size=$(cat size)
target="$(humandev $(cat device)) - $(cat model)"

if [ -z "$2" ]; then
	# Only one parameter. Being run for initial autopartitioning.
	target="$target: $(longint2human $size)"
	free_size=$(expr 0000000"$size" : '0*\(..*\)......$') # convert to megabytes

	choose_recipe default "$target" "$free_size" || exit $?

	auto_init_disk "$dev" || exit $?
else
	# Two parameters, being run on selected free space.
	free_space=$2
	
	open_dialog PARTITION_INFO $free_space
	read_line x1 x2 free_size x3 x4 x5 x6
	close_dialog

	target="$target: $(longint2human $free_size) ($(longint2human $size))"
	free_size=$(expr 0000000"$free_size" : '0*\(..*\)......$') # convert to megabytes

	choose_recipe default "$target" "$free_size" || exit $?
fi

perform_recipe $dev $free_space $recipe || exit $?

# default to accepting the autopartitioning
menudir_default_choice /lib/partman/choose_partition finish finish || true
