#! /bin/sh -e
#
# we need to setup apt before we can use this (cdrom / network)
# see compat/apt-install in ubiquity, and install.py for blocking
# currently just logging

for package; do
	echo "apt-install: $package" >> /var/log/di-live.log
done

