#!/bin/sh
set -e

# This script sets the esp flag for partition whose method is efi
# and removes it for partitions whose method is not efi except
# unused existing ESP.

if [ ! -d /sys/firmware/efi ]; then
	exit 0
fi

. /lib/partman/lib/base.sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
shift; shift; shift; shift; shift; shift; shift
name=$*

cd $dev

if [ $fs = free ]; then
	exit 0
fi

method=
if [ -f $id/method ]; then
	method=$(cat $id/method)
fi

esp=
flags=''
open_dialog GET_FLAGS $id
while { read_line flag; [ "$flag" ]; }; do
	if [ "$flag" = esp ]; then
		esp=yes
	else
		flags="${flags:+$flags$NL}$flag"
	fi
done
close_dialog

open_dialog USES_NAMES
read_line uses_names
close_dialog

if [ "$esp" != yes ] && { [ "$method" = efi ] || \
   { [ -z "$method" ] && [ -f $id/old_efi ]; }; }; then
	log "efi_debug: set esp flag on partition $path"
	open_dialog SET_FLAGS $id
	write_line "$flags"
	write_line esp
	write_line NO_MORE
	close_dialog
	if [ "$uses_names" = yes ] && [ "$fs" = fat32 ]; then
		open_dialog SET_NAME $id "EFI System Partition"
		close_dialog
	fi
	RET=''
elif [ "$esp" = yes ] && [ "$method" != efi ] && \
     { [ -n "$method" ] || [ ! -f $id/old_efi ]; }; then
	log "efi_debug: remove esp flag from partition $path"
	open_dialog SET_FLAGS $id
	write_line "$flags"
	write_line NO_MORE
	close_dialog
	if [ "$uses_names" = yes ] && [ "$fs" = fat32 ] && \
	   [ "$name" = "EFI System Partition" ]; then
		open_dialog SET_NAME $id ""
		close_dialog
	fi
fi
