from _typeshed import Incomplete
from collections.abc import Sequence

LOGFILE: str
PIPE: Incomplete

def log(msg: str) -> None: ...

class Chroot:
    real_root: Incomplete
    initial_cwd: Incomplete
    environ: Incomplete
    targetmounts: Incomplete
    def __init__(self, newroot: str, environ: dict[str, str] | None = None) -> None: ...
    def system(self, command: str | list[str], shell: bool = False, stdout: int | None = None) -> None: ...
    def exit(self) -> None: ...
    def __del__(self) -> None: ...

class DiliveDebconf:
    db: Incomplete
    def __init__(self, title: str | None = None) -> None: ...
    def get_input(self, template: str = 'di-live/get-string', description: str | None = None, default: str | None = None) -> str: ...
    def get_password(self, description: str, allow_empty: bool = False) -> str: ...
    progress_steps: Incomplete
    def progress_init(self, steps: int, template: str = 'di-live/progress/generic', description: str | None = None) -> None: ...
    def progress_step(self, step_no: int) -> None: ...

class TargetMounts:
    targetdev: Incomplete
    targetproc: Incomplete
    targetsys: Incomplete
    targetrun: Incomplete
    def __init__(self, target: str = '/target') -> None: ...
    def mount(self) -> None: ...
    def umount(self) -> None: ...
    def __del__(self) -> None: ...

class ExecError(Exception):
    command: Incomplete
    exitcode: Incomplete
    def __init__(self, command: str, exitcode: int) -> None: ...

def prepend_path(path: str) -> None: ...
def system(command: str | list[str], shell: bool = False, stdout: int | None = None, write_log: bool = True, env: dict[str, str] | None = None) -> None: ...
def dilive_system(command: list[str]) -> None: ...
def preset_debconf(resets: list[str] | None = None, preseeds: Sequence[tuple[str, str | bool]] | None = None, seen: list[tuple[str, bool]] | None = None) -> None: ...
def is_mounted(directory: str) -> bool: ...
def target_mounted(target: str = '/target') -> bool: ...
