import types
from _typeshed import Incomplete

class DebconfError(Exception): ...

LOW: Incomplete
MEDIUM: Incomplete
HIGH: Incomplete
CRITICAL: Incomplete

class Debconf:
    read: Incomplete
    write: Incomplete
    def __init__(self, title=None, read=None, write=None, run_frontend: bool = False) -> None: ...
    version: Incomplete
    capabilities: Incomplete
    def setUp(self, title) -> None: ...
    def setCommand(self, command): ...
    def command(self, command, *params): ...
    def stop(self) -> None: ...
    def forceInput(self, priority, question): ...
    def getBoolean(self, question): ...
    def getString(self, question): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    # dynamic methods added by gen_type_stubs.py
    def capb(self, arg: str) -> None: ...
    def metaget(self, arg1: str, arg2: str) -> str: ...
    def reset(self, arg: str) -> None: ...
    def subst(self, arg1: str, arg2: str, arg3: str) -> None: ...
    def input(self, arg1: str, arg2: str) -> None: ...
    def go(self) -> None: ...
    def get(self, arg: str) -> str: ...
    def set(self, arg1: str, arg2: str | bool) -> None: ...
    def progress(self, arg: str) -> None: ...
    def fset(self, arg1: str, arg2: str, arg3: bool) -> None: ...

class DebconfCommunicator(Debconf):
    dccomm: Incomplete
    def __init__(self, owner, title=None, cloexec: bool = False) -> None: ...
    def shutdown(self) -> None: ...
    def __del__(self) -> None: ...

def runFrontEnd() -> None: ...
