#!/bin/sh

. /lib/partman/lib/base.sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

cd $dev

if [ $fs = free ]; then
	rm -f $id/bootable $id/legacy_boot
else
	bootable=no
	legacy_boot=no
	open_dialog GET_FLAGS $id
	while { read_line flag; [ "$flag" ]; }; do
		if [ "$flag" = boot ]; then
			bootable=yes
		elif [ "$flag" = legacy_boot ]; then
			legacy_boot=yes
		fi
	done
	close_dialog

	if [ $bootable = yes ]; then
		mkdir -p $id
		>$id/bootable
	else
		rm -f $id/bootable
	fi

	if [ $legacy_boot = yes ]; then
		mkdir -p $id
		>$id/legacy_boot
	else
		rm -f $id/legacy_boot
	fi
fi
