#!/bin/sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
shift; shift; shift; shift; shift; shift; shift
name=$*

cd $dev

mkdir -p $id

if [ ! -f visuals ]; then
    for i in /lib/partman/valid_visuals.d/*; do
	if [ -x "$i" ]; then $i; fi
    done | 
    sed 's/	.*//' | 
    grep '^number$\|^type$\|^size$\|^name$\|^filesystem$\|^bootable$\|^method$\|^mountpoint$' >visuals 
fi

visuals=$(cat visuals)

for v in $visuals; do
    /lib/partman/visual.d/$v $dev $num $id $size $type $fs $path $name
done >$id/view
