#!/bin/sh

. /usr/share/debconf/confmodule

dev=$1
id=$2

if [ ! -d /sys/firmware/efi ]; then
	exit 0
fi

if [ -f /var/lib/partman/ignore_uefi ]; then
	exit 0
fi

db_metaget partman-efi/text/efi description

printf "efi\t${RET}\n"
