#!/bin/sh

. /lib/partman/lib/base.sh

for dev in /var/lib/partman/devices/*; do
    [ -d "$dev" ] || continue
    cd $dev
    partitions=
    open_dialog PARTITIONS
    while { read_line partinfo; [ "$partinfo" ]; }; do
	if [ "$partitions" ]; then
	    partitions="$partitions
$partinfo"
	else
	    partitions="$partinfo"
	fi
    done
    close_dialog

    IFS="$NL"
    for partinfo in $partitions; do
	restore_ifs
	for u in /lib/partman/update.d/*; do
	    [ -x "$u" ] || continue
	    $u $dev $partinfo
	done
	IFS="$NL"
    done
    restore_ifs
done

