#!/bin/sh

. /lib/partman/lib/base.sh

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

open_dialog GET_LABEL_TYPE
read_line label
close_dialog

if [ "$label" != gpt -a -f $id/bootable ] || \
   [ "$label" = gpt -a -f $id/legacy_boot ]; then
	printf "B"
fi
