#!/bin/sh

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

if [ -f $id/visual_mountpoint ]; then
    mountpoint=$(cat $id/visual_mountpoint)
else
    mountpoint=''
fi

printf " %-20s" "$mountpoint"
