#!/bin/sh

. /usr/share/debconf/confmodule

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

if [ "$fs" = free ]; then
    printf "%${number_width}s" ''
else
    db_metaget partman/text/number description
    x=$(printf "$RET" $num)
    stralign "$number_width" "$x"
fi
