#!/usr/bin/python
# Copyright (c) 2008 Alon Swartz <alon@turnkeylinux.com> - all rights reserved

from common import dilive_system

def main():
    dilive_system('/lib/live-installer/live-installer')


if __name__ == "__main__":
    main()

