#!/usr/bin/python

from common import prepend_path, system

def main():
    prepend_path('/usr/lib/di-live/compat')
    system('/lib/live-installer/live-installer')


if __name__ == "__main__":
    main()

