#!/usr/bin/python3
# Copyright (c) 2008 Alon Swartz <alon@turnkeylinux.org> - all rights reserved

import os
import debconf

from common import system


def deep_umount(target):
    paths = []
    with open("/proc/mounts", 'r') as fob:
        for mount in fob.readlines():
            path = mount.split()[1]
            if path.startswith(target):
                paths.append(path)

    paths.sort(reverse=True)
    for path in paths:
        try:
            system("umount", "-f", path)
        except:
            pass


def reboot():
    template = 'di-live/reboot_now'

    debconf.runFrontEnd()
    db = debconf.Debconf()

    db.capb('backup')
    db.reset(template)
    db.input(debconf.HIGH, template)
    db.go()

    cmd = []
    fgvt = os.environ.get("FGVT")
    if fgvt:
        cmd.append("chvt %s" % fgvt)

    if db.getBoolean(template):
        cmd.append("systemctl reboot")

    if cmd:
        system("; ".join(cmd))


def main():
    deep_umount('/target')
    with open('/tmp/.di-live-finalize', 'w') as fob:
        fob.write('')
    reboot()


if __name__ == "__main__":
    main()
