#!/usr/bin/python

import debconf

from common import system

def main():
    template = 'di-live/reboot_now'

    debconf.runFrontEnd()
    db = debconf.Debconf()

    db.reset(template)
    db.input(debconf.HIGH, template)
    db.go()

    if db.getBoolean(template):
        system("reboot")

if __name__ == "__main__":
    main()

