#!/bin/sh

mkdir -p /var/lib/partman

cat /proc/modules |
while read module_name x; do
	if [ "$module_name" = ext3 ]; then
		>/var/lib/partman/ext3
		exit 0
	fi
done

if modprobe ext3 >/dev/null 2>/dev/null; then
	>/var/lib/partman/ext3
	exit 0
fi

if grep -q ext3 /proc/filesystems; then
	>/var/lib/partman/ext3
fi
