#!/bin/sh -e

# Debian (live-boot)
PLACES="$PLACES /cdrom/live/filesystem.dir"
# Ubuntu (casper)
PLACES="$PLACES /cdrom/casper/filesystem.dir"

dir_prepare() {
	cd $place
}

dir_teardown() {
	:
}

dir_count() {
	echo `find . | wc -l`
}
